name: ChatEmotesPE
version: 1.0
api: 4.0.0
author: PmCodeZ
authors:
  - N0aah02
  - eyNoah

main: CEPE\ChatEmotesPE

website: dsc.gg/pmcoder

permissions:
  cepe.use:
    default: op
    description: "To manage the Commands"
